stages:
  - first
  - second
env:
  - BUILD_TYPE=Release
  - BUILD_TYPE=Debug
os:
  - windows
  - osx
  - linux
  
language: cpp
name: "Build natives"
  
script: echo 'executing common build script ${os} ${BUILD_TYPE} with ${GENERATOR}'
  
matrix:
  include:
  - os: windows
    env: GENERATOR="Visual Studio 15 2017 Win64"
  - os: linux
    env: GENERATOR="Unix Makefiles"
  - os: osx
    env: GENERATOR="Unix Makefiles"
  
matrix:
  - include:
    - stage: second
      os: linux
      dist: trusty
      language: java
      script:
      - echo 'custom script on second stage'
