stages:
  - first
  - second
env:
  - BUILD_TYPE=Release
  - BUILD_TYPE=Debug
  - BUILD_TYPE=RelWithDebugInfo
os:
  - windows
  - osx
  - linux
  
language: cpp
name: "Build natives"
  
script: echo 'executing common build script ${os} ${BUILD_TYPE} with ${GENERATOR}'
  
jobs:
  - include:
    - stage: first
      os: windows
      env:
        global:
        - GENERATOR="Visual Studio 15 2017 Win64"
        matrix:
        - BUILD_TYPE=Debug
        - BUILD_TYPE=Release
        - BUILD_TYPE=RelWithDebugInfo
    - stage: first
      os: linux
      env:
        global:
        - GENERATOR="Unix Makefiles"
        matrix:
        - BUILD_TYPE=Debug
        - BUILD_TYPE=Release
        - BUILD_TYPE=RelWithDebugInfo
