stages:
  - first
  - second
  
env:
  matrix:
    - BUILD_TYPE=Release
    - BULID_TYPE=Debug

os:
  - windows
  - osx
  - linux
  

  
script: echo 'executing common build script ${os} ${BUILD_TYPE}'
  
jobs:
  - include:
    - stage: first
      os: windows
      env:
        GENERATOR="Visual Studio 15 2017 Win64"
    - stage: first
      os: osx
      env:
        GENERATOR="Unix Makefiles"
    - stage: first
      os: linux
      env:
        GENERATOR="Unix Makefiles"
    - stage: second
      os: linux
      script:
      - echo 'custom script on second stage'
