stages:
  - first
  - second
env:
  matrix:
    - BUILD_TYPE=Release
    - BUILD_TYPE=Debug
os:
  - windows
  - osx
  - linux
  
language: cpp
name: "${os} ${BUILD_TYPE}"
  
script: echo 'executing common build script ${os} ${BUILD_TYPE} with ${GENERATOR}'
  
jobs:
  - include:
    - stage: first
      os: windows
      env:
        GENERATOR="Visual Studio 15 2017 Win64"
    - stage: first
      os: osx
      env:
        GENERATOR="Unix Makefiles"
    - stage: first
      os: linux
      dist: trusty
      env:
        GENERATOR="Unix Makefiles"
    - stage: second
      os: linux
      dist: trusty
      language: java
      script:
      - echo 'custom script on second stage'
