stages:
  - first
  - second
env:
  - BUILD_TYPE=Release
  - BUILD_TYPE=Debug
  - BUILD_TYPE=RelWithDebugInfo
  - GENERATOR="Unix Makefiles"
  - GENERATOR="Visual Studio 15 2017 Win64"
os:
  - windows
  - osx
  - linux
  
language: cpp
name: "Build natives"
  
script: 
- env
- echo "executing common build script ${os} ${BUILD_TYPE} with ${GENERATOR}"
  
matrix:
  include:
  - stage: first
    os: windows
    env: GENERATOR="Visual Studio 15 2017 Win64"
  - stage: first
    os: linux
    env: GENERATOR="Unix Makefiles"
  - stage: first
    os: osx
    env: GENERATOR="Unix Makefiles"
