stages:
  - first
  - second

stage: first
language: cpp
  
script: 
- env
- echo "executing common build script ${TRAVIS_OS_NAME} ${BUILD_TYPE} with ${GENERATOR}"

install:
- |
  set -ex
  case "${TRAVIS_OS_NAME}" in
    windows)
      choco install awscli
      choco install cmake --version 3.13.0
      choco install jdk8
      choco install visualstudio2017buildtools
      choco install visualstudio2017-workload-vctools
      choco install visualstudio2017-workload-nativedesktop
    ;;
    linux)
      sudo apt-get install -y freeglut3-dev
      pip install --user awscli
      pip install --user cmake=3.13.0
    ;;
    osx)
      brew desc cmake
      brew info cmake
    ;;
  esac
  set +ex

matrix:
  include:
  - os: windows
    env: BUILD_TYPE=Release GENERATOR="Visual Studio 15 2017 Win64"
  - os: windows  
    env: BUILD_TYPE=Debug GENERATOR="Visual Studio 15 2017 Win64"
  - os: windows
    env: BUILD_TYPE=RelWithDebugInfo GENERATOR="Visual Studio 15 2017 Win64"
  - os: linux
    dist: trusty
    env: BUILD_TYPE=Release GENERATOR="Unix Makefiles"
  - os: linux
    dist: trusty
    env: BUILD_TYPE=Debug GENERATOR="Unix Makefiles"
  - os: linux
    dist: trusty
    env: BUILD_TYPE=RelWithDebugInfo GENERATOR="Unix Makefiles"
  - os: osx
    env: BUILD_TYPE=Release GENERATOR="Unix Makefiles"
  - os: osx
    env: BUILD_TYPE=Debug GENERATOR="Unix Makefiles"
  - os: osx
    env: BUILD_TYPE=RelWithDebugInfo GENERATOR="Unix Makefiles"
  - stage: second
    os: linux
    dist: trusty
    script: echo "and the final one"
