stages:
  - first
  - second

stage: first
language: cpp
  
script: 
- env
- echo "executing common build script ${TRAVIS_OS_NAME} ${BUILD_TYPE} with ${GENERATOR}"

matrix:
  include:
  - os: windows
    env: BUILD_TYPE=Release GENERATOR="Visual Studio 15 2017 Win64"
  - os: windows  
    env: BUILD_TYPE=Debug GENERATOR="Visual Studio 15 2017 Win64"
  - os: windows
    env: BUILD_TYPE=RelWithDebugInfo GENERATOR="Visual Studio 15 2017 Win64"
  - os: linux
    env: BUILD_TYPE=Release GENERATOR="Unix Makefiles"
  - os: linux
    env: BUILD_TYPE=Debug GENERATOR="Unix Makefiles"
  - os: linux
    env: BUILD_TYPE=RelWithDebugInfo GENERATOR="Unix Makefiles"
  - os: osx
    env: BUILD_TYPE=Release GENERATOR="Unix Makefiles"
  - os: osx
    env: BUILD_TYPE=Debug GENERATOR="Unix Makefiles"
  - os: osx
    env: BUILD_TYPE=RelWithDebugInfo GENERATOR="Unix Makefiles"
  - stage: second
    os: linux
    dist: trusty
    script: echo "and the final one"
