stages:
  - first
  - second
env:
  - BUILD_TYPE=Release GENERATOR="Unix Makefiles"
  - BUILD_TYPE=Debug GENERATOR="Unix Makefiles"
  - BUILD_TYPE=RelWithDebugInfo GENERATOR="Unix Makefiles"
  - BUILD_TYPE=Release GENERATOR="Visual Studio 15 2017 Win64"
  - BUILD_TYPE=Debug GENERATOR="Visual Studio 15 2017 Win64"
  - BUILD_TYPE=RelWithDebugInfo GENERATOR="Visual Studio 15 2017 Win64"
os:
  - windows
  - osx
  - linux
  
language: cpp
name: "Build natives"
  
script: 
- env
- echo "executing common build script ${os} ${BUILD_TYPE} with ${GENERATOR}"
  
matrix:
  include:
  - stage: first
    os: windows
    env:
    - BUILD_TYPE=Release GENERATOR="Visual Studio 15 2017 Win64"
    - BUILD_TYPE=Debug GENERATOR="Visual Studio 15 2017 Win64"
    - BUILD_TYPE=RelWithDebugInfo GENERATOR="Visual Studio 15 2017 Win64"
  - stage: first
    os: linux
    env:
    - BUILD_TYPE=Release GENERATOR="Unix Makefiles"
    - BUILD_TYPE=Debug GENERATOR="Unix Makefiles"
    - BUILD_TYPE=RelWithDebugInfo GENERATOR="Unix Makefiles"
  - stage: first
    os: osx
    env:
    - BUILD_TYPE=Release GENERATOR="Unix Makefiles"
    - BUILD_TYPE=Debug GENERATOR="Unix Makefiles"
    - BUILD_TYPE=RelWithDebugInfo GENERATOR="Unix Makefiles"
